### ISSUE TITLE
fix this

### ISSUE THREAD

**Issue by flashwave** [flashii/sharp-chat#1]
```
7/9/19 4:57:04 PM [Error] Application Error System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at SharpChat.SockChatUser.Close() in /home/flash/sharp-chat/SharpChat/SockChatUser.cs:line 110
   at SharpChat.SockChatContext.BanUser(SockChatUser user, Nullable`1 until, Boolean banIPs, String type) in /home/flash/sharp-chat/SharpChat/SockChatContext.cs:line 77
   at SharpChat.SockChatServer.OnMessage(IWebSocketConnection conn, String msg) in /home/flash/sharp-chat/SharpChat/SockChatServer.cs:line 95
   at Fleck.Handlers.Hybi13Handler.<>c__DisplayClass0_0.<Create>b__7(FrameType op, Byte[] data)
   at Fleck.Handlers.Hybi13Handler.ReceiveData(List`1 data, ReadState readState, Action`2 processFrame)
   at Fleck.WebSocketConnection.<>c__DisplayClass59_0.<Read>b__0(Int32 r)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
```

**Comment by flashwave** [comment]
it doesn't seem to be happening anymore yay
